const meta = {
  "building-api-gateway-golang-performance-concurrency": "Building an API Gateway in Go: A Thought Process Focused on Performance and Concurrency",
  "multi-tenant-saas-isolation-patterns": "Multi-Tenant SaaS at Scale: Isolation Beyond RLS",
  "postgres-first-architecture": "The Postgres-First Architecture",
  "cursor-vs-offset-pagination": "Cursor vs Offset Pagination: What Actually Works at Scale?",
  "kafka-pulsar-nats-2026": "Kafka, Pulsar, NATS JetStream in 2026",
  "event-driven-vs-request-driven-architectures": "Event-Driven vs Request-Driven Architectures: When to Use What",
  "durable-workflows-2026": "Durable Workflows in 2026",
  "cache-invalidation-at-scale": "Cache Invalidation at Scale",
  "graceful-degradation-beyond-circuit-breakers": "Graceful Degradation: Beyond Circuit Breakers",
  "idempotency-every-layer": "Idempotency at Every Layer",
  "zero-downtime-db-migrations": "Zero-Downtime Database Migrations",
  "service-mesh-overrated": "Service Mesh Is Overrated for Most Teams",
  "xds-rest-vs-grpc-config-push": "xDS REST and gRPC for Config Push Between Control Plane and Data Plane",
  "finops-cloud-native-right-size": "FinOps for Cloud-Native: Right-Size Before Refactor",
  "best-api-gateway-2026-comparison": "Choosing the Right API Gateway in 2026",
  "building-enterprise-rag-chatbot-that-works": "Building a RAG Chatbot for Enterprise Products That Actually Works",
  "understanding-grpc-protobuf-rest-graphql": "Understanding gRPC in Depth: Protobuf, REST, and GraphQL",
  "fastest-golang-web-frameworks-and-when-to-choose": "The Fastest Golang Web Frameworks and When to Choose Which",
  "nodejs-in-production": "Running Node.js in production",
  "vibe-coding-explained": "Vibe Coding Explained",
  "handle-1m-rps-nodejs": "How to Handle 1M+ Requests/Second in Node.js",
  "agentic-ai-guardrails": "Guardrails for agentic AI",
  "scaling-apis-bfsi": "Scaling API gateways for BFSI",
};

export default meta;
